services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args: 
        NODE_ENV: production
    image: items-comparison:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SEED=true
      - COUNT=30
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data:/application/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"